import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useContext, useState, useEffect } from 'react';

// auth
import AuthCheck from '../components/AuthCheck';
import { auth, firestore } from '../lib/auth/firebase';
import { useDocumentData, useCollectionData, useCollection } from 'react-firebase-hooks/firestore'
import { UserContext } from '../lib/auth/context';

export default function Home() {
  const { user } = useContext(UserContext);
  const [isSSR, setIsSSR] = useState(true);

  useEffect(() => {
    setIsSSR(false);
  }, []);

  return (
    !isSSR &&
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Приветствую на <a href="https://nextjs.org">BikeJS!</a>
        </h1>

        <p className={styles.description}>
          <AuthCheck>
            <p>Есть пользователь!</p>
            <p>{user && user.email}, {user && user.uid}</p>
            <a href='/profile'>Личный кабинет</a>
            <br/>
            <button
              onClick={async (e) => {
                e.preventDefault();
                auth.signOut()
              }}
            >
              Вылогиниться
            </button>
          </AuthCheck>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="epinetov.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Epinetov
        </a>
      </footer>
    </div>
  )
}
